server.port: 9090
spring.datasource.url: jdbc:sqlserver://terasyncdb.cp4caykesns8.eu-north-1.rds.amazonaws.com:1433
spring.datasource.username: admin
spring.datasource.password: JkAXj5n7kGtSrAx
spring.datasource.driver.class: org.sqlserver.Driver
