INSERT INTO Customer (firstName, lastName, email, username, password)
VALUES
    ('John', 'Doe', 'john.doe@example.com', 'johndoe', 'password1'),
    ('Jane', 'Smith', 'jane.smith@example.com', 'janesmith', 'password2'),
    ('Michael', 'Johnson', 'michael.johnson@example.com', 'michaelj', 'password3'),
    ('Emily', 'Brown', 'emily.brown@example.com', 'emilyb', 'password4'),
    ('David', 'Martinez', 'david.martinez@example.com', 'davidm', 'password5'),
    ('Sarah', 'Anderson', 'sarah.anderson@example.com', 'saraha', 'password6'),
    ('James', 'Taylor', 'james.taylor@example.com', 'jamest', 'password7'),
    ('Jessica', 'Thomas', 'jessica.thomas@example.com', 'jessicat', 'password8'),
    ('Christopher', 'Hernandez', 'christopher.hernandez@example.com', 'christopherh', 'password9'),
    ('Ashley', 'Moore', 'ashley.moore@example.com', 'ashleym', 'password10'),
    ('Matthew', 'Wilson', 'matthew.wilson@example.com', 'mattheww', 'password11'),
    ('Amanda', 'Garcia', 'amanda.garcia@example.com', 'amandag', 'password12'),
    ('Andrew', 'Lopez', 'andrew.lopez@example.com', 'andrewl', 'password13'),
    ('Elizabeth', 'Hill', 'elizabeth.hill@example.com', 'elizabethh', 'password14'),
    ('Joshua', 'Scott', 'joshua.scott@example.com', 'joshuas', 'password15'),
    ('Jennifer', 'Green', 'jennifer.green@example.com', 'jenniferg', 'password16'),
    ('Justin', 'Adams', 'justin.adams@example.com', 'justina', 'password17'),
    ('Samantha', 'Baker', 'samantha.baker@example.com', 'samanthab', 'password18'),
    ('Robert', 'Perez', 'robert.perez@example.com', 'robertp', 'password19'),
    ('Stephanie', 'Campbell', 'stephanie.campbell@example.com', 'stephaniec', 'password20'),
    ('Daniel', 'Rivera', 'daniel.rivera@example.com', 'danielr', 'password21');

INSERT INTO DeliveryService (name, email, username, password)
VALUES
    ('FastDelivery', 'fastdelivery@example.com', 'fastdelivery', 'password1'),
    ('SwiftShip', 'swiftship@example.com', 'swiftship', 'password2'),
    ('ExpressMovers', 'expressmovers@example.com', 'expressmovers', 'password3'),
    ('SpeedyCouriers', 'speedycouriers@example.com', 'speedycouriers', 'password4'),
    ('QuickDispatch', 'quickdispatch@example.com', 'quickdispatch', 'password5'),
    ('RapidTransit', 'rapidtransit@example.com', 'rapidtransit', 'password6'),
    ('ZoomDelivery', 'zoomdelivery@example.com', 'zoomdelivery', 'password7'),
    ('PrimeShippers', 'primeshippers@example.com', 'primeshippers', 'password8'),
    ('AeroExpress', 'aeroexpress@example.com', 'aeroexpress', 'password9'),
    ('PrestigeLogistics', 'prestigelogistics@example.com', 'prestigelogistics', 'password10'),
    ('EagleCarriers', 'eaglecarriers@example.com', 'eaglecarriers', 'password11'),
    ('EliteHaulage', 'elitehaulage@example.com', 'elitehaulage', 'password12'),
    ('StarTrans', 'startrans@example.com', 'startrans', 'password13'),
    ('QuickCargo', 'quickcargo@example.com', 'quickcargo', 'password14'),
    ('RedRocket', 'redrocket@example.com', 'redrocket', 'password15'),
    ('SpeedyFreight', 'speedyfreight@example.com', 'speedyfreight', 'password16'),
    ('ExpressTruckers', 'expresstruckers@example.com', 'expresstruckers', 'password17'),
    ('TurboLogistics', 'turbologistics@example.com', 'turbologistics', 'password18'),
    ('RapidRiders', 'rapidriders@example.com', 'rapidriders', 'password19'),
    ('SwiftCarriers', 'swiftcarriers@example.com', 'swiftcarriers', 'password20'),
    ('VelocityMovers', 'velocitymovers@example.com', 'velocitymovers', 'password21');